version: '2'

services:
    redis:
        image: redis:alpine
    snappass:
        image: nemoinho/snappass
        environment:
            - REDIS_HOST=redis
        depends_on:
            - redis
        ports:
            - 5000:5000
